GDB-7678: Set up a GitHub repository for the "ontotext-yasgui" component
Ontotext-AD/ontotext-yasgui pull request #1
Opened 2022-12-06 12:03 UTC by boyan-tonchev

What?

  An initial commitment of "ontotext-yasgui" projects.

Why?

  We need a repository where to manage customization of yasgui component.

How?

  A repository "ontotext-yasgui" is created. It holds three projects.
  - Yasgui - holds source code of original yasgui-component;
  - ontotext-yasgui - holds ontotext customizations;
  - cypress - holds e2e tests.

2022-12-06 12:58 UTC, svilenvelikov requested changes

2022-12-06 12:58 UTC, svilenvelikov commented on README.md
> +# Approach for the component implementation
This should be in the developers-guide. Maybe here we should just link to it here.

2022-12-06 12:58 UTC, svilenvelikov commented on README.md
> +# Dev server
Change to `Starting a development server`

2022-12-06 12:58 UTC, svilenvelikov commented on package.json
> +  "version": "1.0.0",
Make this `0.0.1`

2022-12-06 12:58 UTC, svilenvelikov commented on package.json
> +  "name": "ontotext-yasgui-web-component",
Didn't we decided to name it `ontotext-yasgui` and the inner ontotext-yasgui to be `ontotext-yasgui-web-component`.

2022-12-06 17:11 UTC, boyan-tonchev commented on package.json
> +  "version": "1.0.0",
done

2022-12-07 06:35 UTC, svilenvelikov approved these changes

2022-12-07 06:48 UTC, merged