Added internationalization to YASGUI, YASQE and YASR
Ontotext-AD/ontotext-yasgui pull request #40
Opened 2023-01-06 16:14 UTC by boyan-tonchev

## What
- Added language support to YASGUI, YASQE and YASR.

## Why
- ontotext-yasgui clients needs language support.

## How
- YASGUI, YASQE and YASR don’t support transaction by default. The library configurations are extended to support translation function which will be used for translation. When the configurations are prepared the "translate" method of TranslationService is passed as value.

Additional work:
 * extends configuration to show yasgui control bar;
 * Added patch with changes in YASGUI, YASQE and YASR.

2023-01-09 16:44 UTC, svilenvelikov requested changes

2023-01-09 16:44 UTC, svilenvelikov commented on ontotext-yasgui-web-component/src/components/ontotext-yasgui-web-component/ontotext-yasgui-web-component.scss
> +  .hidden-control-bar {
Can we just use the `hidden` class we already have instead of adding another one with the exact same purpose.

2023-01-09 19:13 UTC, boyan-tonchev commented on Yasgui/packages/yasgui/src/TabPanel.ts
> +    while (this.settingsButton.firstChild) {
Removes all children of "this.settingsButton". This button has a Svg element as child. The title of svg is displayed and I had to translate it. I tried to change it as other elements but without success (may be this is of svg nature, I am not sure whty). So here I delete the old svg and create a new one with the new label.

2023-01-10 16:55 UTC, boyan-tonchev commented on Yasgui/packages/yasgui/src/TabPanel.ts
> +  private updateLabelFunctions: Function[] | null = [];
Done

2023-01-10 16:56 UTC, boyan-tonchev commented on Yasgui/packages/yasgui/src/TabPanel.ts
> +    this.updateLabelFunctions = [];
Removed

2023-01-10 16:56 UTC, boyan-tonchev commented on Yasgui/packages/yasgui/src/TabPanel.ts
> +    this.updateLabelFunctions = null;
Done

2023-01-10 16:56 UTC, boyan-tonchev commented on Yasgui/packages/yasgui/src/TabPanel.ts
> +    this.updateLabelFunctions?.forEach((updateLabelFunction) => updateLabelFunction());
Done

2023-01-10 17:06 UTC, boyan-tonchev commented on Yasgui/packages/yasgui/src/TabPanel.ts
> +    const updateLabelFunction = (labelKey: string) => (labelElement: HTMLElement) => {
Done

2023-01-11 11:22 UTC, svilenvelikov approved these changes

2023-01-11 12:12 UTC, boyan-tonchev commented
Jenkins retry build

2023-01-11 12:13 UTC, boyan-tonchev commented
Jenkins retry build

2023-01-11 12:20 UTC, merged