GDB-8022: add keyboard shortcut dialog
Ontotext-AD/ontotext-yasgui pull request #83
Opened 2023-03-09 12:12 UTC by boyan-tonchev

## What
Added button in right bottom corner of YASQE. When button is clicked a dialog is opened with description of all keyboard shortcuts which "ontotext-yasgui-web-component" supports.

## Why
"ontotext-yasgui-web-component" supports some keyboard shortcuts, and we have to inform user of component how to use them.

## How
- Implement a "keyboard-shortcuts-dialog" component.
- Implement abstraction about creation of keyboard shortcuts description into dialog and registration of shortcuts.

2023-03-09 12:18 UTC, boyan-tonchev commented
Jenkins retry

2023-03-13 08:31 UTC, svilenvelikov requested changes

2023-03-13 08:31 UTC, svilenvelikov commented on ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
> +      keyboardShortcutDescription.keyboardShortcuts.forEach(keyboardShortcut => {
Replace these nested loops with map->forEach or map->map

2023-03-13 08:31 UTC, svilenvelikov commented on ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
> +    config.yasguiConfig.yasqe.keyboardShortcutDescriptions = keyboardShortcutDescriptions.map(keyboardShortcutDescription => keyboardShortcutDescription.NAME.toString());
Maybe use toLowerCase or even change the enum KeyboardShortcutName values to be lowercase

2023-03-13 10:57 UTC, svilenvelikov commented on ontotext-yasgui-web-component/src/components/ontotext-dialog-web-component/ontotext-dialog-web-component.scss
> +  //display: block;
delete it

2023-03-13 11:03 UTC, svilenvelikov commented on ontotext-yasgui-web-component/src/services/yasgui/configuration/yasgui-configuration-builder.ts
> +    config.yasguiConfig.yasqe.extraKeys = keyboardShortcutDescriptions.reduce((extra, keyboardShortcutDescription) => {
Again, you can can avoid this nesting and complexity by flattening this by just mapping the keyboardShortcutDescriptions and then either reduce or loop-assign as in your first implementation.

2023-03-13 12:35 UTC, boyan-tonchev commented
Jenkins retry

2023-03-13 12:45 UTC, boyan-tonchev commented
Jenkins retry

2023-03-13 13:31 UTC, boyan-tonchev commented
Jenkins rebuild

2023-03-13 13:31 UTC, boyan-tonchev commented
Jenkins retry

2023-03-13 13:35 UTC, boyan-tonchev commented
Jenkins retry

2023-03-13 13:44 UTC, boyan-tonchev commented
Jenkins retry

2023-03-14 09:40 UTC, merged